apiVersion: v1
kind: ConfigMap
metadata: 
    name: mongodb-config
immutable: false
data:
    username: admin
    password: private
    sample.conf: |
        This is a test file
        with multiple lines
